travis:
  secure:
    BINSTAR_TOKEN: nsN0cvdkUBvyqITczP602pSqz1MioVU+rGTGHzjoGZ1/B2covw3vF8gFm5ZB3VVBZ/ZBgarcOQWOLS6efVdzg6p2wl0UDBqd3pjM/OZzKbTsHq4X8K9XYS7o1gbnmKPVFMsMk7b2eedCix9TKrJLTwpd958djJCn9TCrR2/A4j46T9mptxd+vGSs/BShKPBPVfgW4NT5SnKnjguA1C9QyOKRym4SblPqci/0tk4+vTYbBAWuZnodLE9Ty2JERYzsEDB9/IiDdSnTWpypA6wU26z5GAkVw1HTozpE/qi1CsREyt2cZeHkcpm2wx9OTe0/r5wEpGiEzbwCiXhdJn+lsAm+ovCmIoxC22xhZzWkAC35cHc3zgUlzaqU+a8SUJj1J6MDVLxnEPVH8F2K80Fv1TY9AQ1eU9bgUJYJDfsbkLi9C0VZK7wC88FnngiIWv+jDDmv/S3rvpbpk/wDKxWBWuQ8Znq0FvVStUrGMqcEjptBIkvLFeZTDXalcF8qaGR6016kBxEcF3TyThk4rC7j+tZ5hVdb+M09HP640eVpRnz8BBx9+ge0Lls/ZIN6NqzXUrje/EyTHe94HuuwzLofXBFRsiiZ/HhL41VaCcLsv3sur2Ef3FHm8PqWjXTBSVXP1S94j6RYf0QrbnqoKqiyWb6jwjS7y3S08NoaQvOT9/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
